hardware:
  pixie:
    firmware: 30474
    frequency: 250

input:
  file_list:
#    - D:/data/svp/kafka-tests/kafka-data-test-0.pld
#    - D:/data/svp/kafka-tests/bagel-single-spill-1.pld
    - D:/data/ithemba/bagel/runs/runBaGeL_337.pld
#    - D:/data/utk/pixieworkshop/pulser_003.ldf
#    - D:/data/anl/vandle2015/a135feb_12.ldf
#    - D:/data/ornl/073cu/cu73_04-1.ldf
#    - D:/data/ornl/073cu/cu73_04-1.ldf


output:
  root: data # The root directory that we'll use to store the output files and meta information
